In [29]:
import numpy as np
from scipy.ndimage import gaussian_filter

def latent_intensity_map_with_groups(N, M, a=1.0, b=5.0, c=1.0, d=5.0, zeros_ratio=0.7, sigma=2):
    x = np.arange(0, N).reshape(-1, 1)
    y = np.arange(0, M).reshape(1, -1)
    
    intensity_map = a * (x - b)**2 + c * (y - d)**2
    
    #noise = np.random.rand(N, M)
   # intensity_map += noise
    
   # intensity_map = gaussian_filter(intensity_map, sigma=sigma)
    
    intensity_map = (intensity_map - np.min(intensity_map)) / (np.max(intensity_map) - np.min(intensity_map))
    
    sorted_intensity = np.sort(intensity_map.flatten())
    threshold_idx = int(zeros_ratio * N * M)
    dynamic_threshold = sorted_intensity[threshold_idx]
    
    binary_map = (intensity_map > dynamic_threshold).astype(int)
    
    return binary_map, intensity_map, dynamic_threshold

N, M = 20, 30
a, b, c, d = 1.0, N/2, 1.0, M/3  
zeros_ratio = 0.3 
sigma = 2  

binary_map, intensity_map, dynamic_threshold = latent_intensity_map_with_groups(N, M, a, b, c, d, zeros_ratio, sigma)

ones_proportion = np.sum(binary_map) / (N * M)
print("Binary Map:")
print(binary_map)
print("Intensity Map:")
print(intensity_map)


Binary Map:
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1

In [33]:
import numpy as np
from scipy.ndimage import gaussian_filter

def latent_intensity_map_random_groups(N, M, num_groups, zeros_ratio=0.7, sigma=2):
    intensity_map = np.zeros((N, M))
    
    x = np.arange(0, N).reshape(-1, 1)
    y = np.arange(0, M).reshape(1, -1)
    
    for _ in range(num_groups):
        a = np.random.uniform(0.5, 1.5)  
        b = np.random.uniform(0, N)      
        c = np.random.uniform(0.5, 1.5)  
        d = np.random.uniform(0, M)      
        
        intensity_map += a * (x - b)**2 + c * (y - d)**2
    
    noise = np.random.rand(N, M)
    intensity_map += noise
    
    # intensity_map = gaussian_filter(intensity_map, sigma=sigma)
    
    intensity_map = (intensity_map - np.min(intensity_map)) / (np.max(intensity_map) - np.min(intensity_map))
    
    sorted_intensity = np.sort(intensity_map.flatten())
    threshold_idx = int(zeros_ratio * N * M)
    dynamic_threshold = sorted_intensity[threshold_idx]
    
    binary_map = (intensity_map > dynamic_threshold).astype(int)
    
    return binary_map, intensity_map, dynamic_threshold

N, M = 20, 30  
num_groups = 2  
zeros_ratio = 0.3 
sigma = 2  


binary_map, intensity_map, dynamic_threshold = latent_intensity_map_random_groups(N, M, num_groups, zeros_ratio, sigma)

ones_proportion = np.sum(binary_map) / (N * M)
print("Binary Map:")
print(binary_map)
print("Intensity Map:")
print(intensity_map)

Binary Map:
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0